# Must change "monorepo-template" to your project name
services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /home/${VPS_USER}/postgres/data:/var/lib/postgresql/data
      - /home/${VPS_USER}/postgres/conf:/etc/postgresql/conf.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Performance tuning parameters
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      TZ: "UTC"
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c work_mem=4MB
      -c max_connections=100
      -c timezone=UTC
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M
    networks:
      - infra

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81" # UI
      - "443:443"
    volumes:
      - /home/${VPS_USER}/nginx-proxy-manager/data:/data
      - /home/${VPS_USER}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - infra

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${VPS_USER}/infra/portainer/data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - infra

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - '2181'
    volumes:
      - /home/${VPS_USER}/zookeeper-data:/var/lib/zookeeper/data
      - /home/${VPS_USER}/zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - infra
    depends_on:
      - zookeeper-permissions

  # Init container to fix permissions
  zookeeper-permissions:
    image: busybox
    user: root
    command: |
      sh -c "
        mkdir -p /var/lib/zookeeper/data /var/lib/zookeeper/log &&
        chown -R 1000:1000 /var/lib/zookeeper/data /var/lib/zookeeper/log &&
        chmod -R 755 /var/lib/zookeeper/data /var/lib/zookeeper/log
      "
    volumes:
      - /home/${VPS_USER}/zookeeper-data:/var/lib/zookeeper/data
      - /home/${VPS_USER}/zookeeper-logs:/var/lib/zookeeper/log

  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-1
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka-1-permissions
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://14.225.198.196:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_PROCESS_ROLES: ''
    volumes:
      - /home/${VPS_USER}/kafka-1-data:/var/lib/kafka/data
    networks:
      - infra

  kafka-1-permissions:
    image: busybox
    user: root
    command: |
      sh -c "
        mkdir -p /var/lib/kafka/data &&
        chown -R 1000:1000 /var/lib/kafka/data &&
        chmod -R 755 /var/lib/kafka/data
      "
    volumes:
      - /home/${VPS_USER}/kafka-1-data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-2
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka-2-permissions
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29093,PLAINTEXT_HOST://14.225.198.196:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_PROCESS_ROLES: ''
    volumes:
      - /home/${VPS_USER}/kafka-2-data:/var/lib/kafka/data
    networks:
      - infra

  kafka-2-permissions:
    image: busybox
    user: root
    command: |
      sh -c "
        mkdir -p /var/lib/kafka/data &&
        chown -R 1000:1000 /var/lib/kafka/data &&
        chmod -R 755 /var/lib/kafka/data
      "
    volumes:
      - /home/${VPS_USER}/kafka-2-data:/var/lib/kafka/data

  kafka-3:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-3
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka-3-permissions
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:29094,PLAINTEXT_HOST://14.225.198.196:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_PROCESS_ROLES: ''
    volumes:
      - /home/${VPS_USER}/kafka-3-data:/var/lib/kafka/data
    networks:
      - infra

  kafka-3-permissions:
    image: busybox
    user: root
    command: |
      sh -c "
        mkdir -p /var/lib/kafka/data &&
        chown -R 1000:1000 /var/lib/kafka/data &&
        chmod -R 755 /var/lib/kafka/data
      "
    volumes:
      - /home/${VPS_USER}/kafka-3-data:/var/lib/kafka/data

  kafka-ui-monorepo-template:
    container_name: kafka_ui_monorepo-template
    image: docker.redpanda.com/redpandadata/console:latest
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: kafka-1:29092,kafka-2:29093,kafka-3:29094
    expose:
      - "8080"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - infra

networks:
  infra:
    name: abc_infra
    external: true