# Must replace all text "monorepo-template" to your project name
services:
  api.monorepo-template:
    image: __API_IMAGE_NAME__
    container_name: monorepo-template-api # Must change name when deploy other projects
    env_file:
      - ./apps/api/envs/.env.base
      - ./apps/api/envs/.env.__ENV__
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TEAMS_WEBHOOK_URL=${TEAMS_WEBHOOK_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - RS_WRITE_KEY=${RS_WRITE_KEY}
      - RS_DATAPLANE_URL=${RS_DATAPLANE_URL}
      - MICROSOFT_GRAPH_TENANT_ID=${MICROSOFT_GRAPH_TENANT_ID}
      - MICROSOFT_GRAPH_CLIENT_ID=${MICROSOFT_GRAPH_CLIENT_ID}
      - MICROSOFT_GRAPH_CLIENT_SECRET=${MICROSOFT_GRAPH_CLIENT_SECRET}
      - MICROSOFT_GRAPH_SERVICE_ACCOUNT_EMAIL=${MICROSOFT_GRAPH_SERVICE_ACCOUNT_EMAIL}
      - MICROSOFT_GRAPH_ENABLED=${MICROSOFT_GRAPH_ENABLED:-false}
    volumes:
      - ./configs/firebase-config.json:/app/config/firebase-config.json:ro
    expose:
      - '3000'
    restart: unless-stopped
    networks:
      - abc_prod_infra
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M

networks:
  abc_prod_infra:
    external: true
