export const API_ENDPOINTS = {
  SIGN_IN: '/api/v1/admin/auth/login',
  SIGN_OUT: '/api/v1/admin/auth/logout',
  REFRESH_TOKEN: '/api/v1/refresh-tokens/refresh',
  USER_PREFERENCES: '/api/v1/users/preferences',
  USERS: '/api/v1/admin/users',
  PROFILE: '/api/v1/users/profile',
  ME: '/api/v1/users/me',
  CHANGE_AVATAR: '/api/v1/users/change-avatar',
  CONTENTS: '/api/v1/admin/contents',
  POSTS: '/api/v1/admin/posts',
  PRODUCTS: '/api/v1/admin/products',
  FILES: '/api/v1/admin/files',
  CATEGORIES: '/api/v1/admin/categories',
  NOTIFICATIONS: '/api/v1/admin/notifications',
  AUDIT_LOGS: '/api/v1/admin/audit-logs',
  CONTACTS: '/api/v1/admin/contacts',
  FAQS: '/api/v1/admin/faqs',
};
