module.exports = {
  insertPragma: false,
  bracketSpacing: true,
  jsxSingleQuote: false,
  requirePragma: false,
  singleQuote: true,
  useTabs: false,
  semi: true,
  tabWidth: 2,
  printWidth: 150,
  proseWrap: 'always',
  arrowParens: 'avoid',
  trailingComma: 'es5',
  quoteProps: 'as-needed',
  htmlWhitespaceSensitivity: 'strict',
  plugins: ['prettier-plugin-tailwindcss'],
};
